version: '3.9'  
  
services:
  db:
    image: mysql:8.0.33-debian
    volumes:
        - ./database/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=projeto_ru_django
    networks:
      - compose_network
  web:
    build: ./projeto-ru
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./projeto-ru:/code/
    ports:
      - "8000:8000"
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=projeto_ru_django
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db
    networks:
      - compose_network

networks:
  compose_network: